"""Data for the five bundled TeleDesign seed systems. Consumed by gen_seeds.py."""

GF = "https://fonts.google.com/specimen/"
OFL = "SIL Open Font License 1.1"

FONTS = {
    "Inter": {"weights": [400, 500, 600, 700], "fallback": "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif", "q": "Inter:wght@400;500;600;700"},
    "JetBrains Mono": {"weights": [400, 500], "fallback": "ui-monospace, 'SFMono-Regular', Consolas, monospace", "q": "JetBrains+Mono:wght@400;500"},
    "Fraunces": {"weights": [400, 600, 700], "fallback": "Georgia, 'Times New Roman', serif", "q": "Fraunces:wght@400;600;700"},
    "Source Serif 4": {"weights": [400, 600], "fallback": "Georgia, 'Times New Roman', serif", "q": "Source+Serif+4:ital,wght@0,400;0,600;1,400"},
    "Instrument Sans": {"weights": [400, 500, 600], "fallback": "ui-sans-serif, system-ui, sans-serif", "q": "Instrument+Sans:wght@400;500;600"},
    "IBM Plex Mono": {"weights": [400, 500, 600], "fallback": "ui-monospace, Consolas, monospace", "q": "IBM+Plex+Mono:wght@400;500;600"},
    "IBM Plex Sans": {"weights": [400, 500, 600], "fallback": "ui-sans-serif, system-ui, sans-serif", "q": "IBM+Plex+Sans:wght@400;500;600"},
    "Manrope": {"weights": [400, 500, 600, 700, 800], "fallback": "ui-sans-serif, system-ui, sans-serif", "q": "Manrope:wght@400;500;600;700;800"},
    "Fredoka": {"weights": [500, 600, 700], "fallback": "ui-rounded, 'Arial Rounded MT Bold', system-ui, sans-serif", "q": "Fredoka:wght@500;600;700"},
    "Nunito": {"weights": [400, 600, 700, 800], "fallback": "ui-rounded, system-ui, sans-serif", "q": "Nunito:wght@400;600;700;800"},
    "DM Mono": {"weights": [400, 500], "fallback": "ui-monospace, Consolas, monospace", "q": "DM+Mono:wght@400;500"},
}

SPACING = [("0", 0), ("px", 1), ("0-5", 2), ("1", 4), ("1-5", 6), ("2", 8), ("3", 12), ("4", 16), ("5", 20),
           ("6", 24), ("8", 32), ("10", 40), ("12", 48), ("16", 64), ("20", 80), ("24", 96)]

SHADCN_CREDIT = {"name": "shadcn/ui", "license": "MIT", "url": "https://github.com/shadcn-ui/ui",
                 "used_for": "Neutral theme colour tokens (apps/v4/registry/themes.ts, oklch), token naming and component inventory"}
OD_CREDIT = {"name": "open-design (nexu-io/open-design) — design-systems/default", "license": "Apache-2.0",
             "url": "https://github.com/nexu-io/open-design",
             "used_for": "Package shape (DESIGN.md + USAGE.md read order) and several agent guidance rules, adapted"}
LUCIDE_CREDIT = {"name": "Lucide", "license": "ISC (Feather-derived icons: MIT)", "url": "https://lucide.dev",
                 "used_for": "Icon library referenced by name; x / search / menu path data inlined in components"}


def _fx(fg="oklch(0.985 0 0)"):
    return fg


SYSTEMS = [
    # ────────────────────────────────────────────────────────────── neutral
    {
        "slug": "neutral", "name": "Neutral", "is_default": True, "default_theme": "light",
        "description": "The default system: shadcn/ui's neutral oklch palette, Inter, 10px base radius. Calm, product-first, works for almost any brief that has no brand of its own.",
        "tags": ["default", "product", "b2b", "dashboard", "shadcn"],
        "fonts": {"display": "Inter", "body": "Inter", "ui": "Inter", "mono": "JetBrains Mono"},
        "light": {
            "background": "oklch(1 0 0)", "foreground": "oklch(0.145 0 0)",
            "card": "oklch(1 0 0)", "card-foreground": "oklch(0.145 0 0)",
            "popover": "oklch(1 0 0)", "popover-foreground": "oklch(0.145 0 0)",
            "primary": "oklch(0.205 0 0)", "primary-foreground": "oklch(0.985 0 0)",
            "secondary": "oklch(0.97 0 0)", "secondary-foreground": "oklch(0.205 0 0)",
            "muted": "oklch(0.97 0 0)", "muted-foreground": "oklch(0.556 0 0)",
            "accent": "oklch(0.97 0 0)", "accent-foreground": "oklch(0.205 0 0)",
            "destructive": "oklch(0.577 0.245 27.325)", "destructive-foreground": "oklch(0.985 0 0)",
            "success": "oklch(0.527 0.137 150.069)", "success-foreground": "oklch(0.985 0 0)",
            "warning": "oklch(0.769 0.165 70.08)", "warning-foreground": "oklch(0.279 0.077 45.635)",
            "border": "oklch(0.922 0 0)", "input": "oklch(0.922 0 0)", "ring": "oklch(0.708 0 0)",
            "chart-1": "oklch(0.87 0 0)", "chart-2": "oklch(0.556 0 0)", "chart-3": "oklch(0.439 0 0)",
            "chart-4": "oklch(0.371 0 0)", "chart-5": "oklch(0.269 0 0)",
        },
        "dark": {
            "background": "oklch(0.145 0 0)", "foreground": "oklch(0.985 0 0)",
            "card": "oklch(0.205 0 0)", "card-foreground": "oklch(0.985 0 0)",
            "popover": "oklch(0.205 0 0)", "popover-foreground": "oklch(0.985 0 0)",
            "primary": "oklch(0.922 0 0)", "primary-foreground": "oklch(0.205 0 0)",
            "secondary": "oklch(0.269 0 0)", "secondary-foreground": "oklch(0.985 0 0)",
            "muted": "oklch(0.269 0 0)", "muted-foreground": "oklch(0.708 0 0)",
            "accent": "oklch(0.269 0 0)", "accent-foreground": "oklch(0.985 0 0)",
            "destructive": "oklch(0.704 0.191 22.216)", "destructive-foreground": "oklch(0.145 0 0)",
            "success": "oklch(0.696 0.17 162.48)", "success-foreground": "oklch(0.205 0 0)",
            "warning": "oklch(0.828 0.189 84.429)", "warning-foreground": "oklch(0.279 0.077 45.635)",
            "border": "oklch(1 0 0 / 10%)", "input": "oklch(1 0 0 / 15%)", "ring": "oklch(0.556 0 0)",
            "chart-1": "oklch(0.87 0 0)", "chart-2": "oklch(0.556 0 0)", "chart-3": "oklch(0.439 0 0)",
            "chart-4": "oklch(0.371 0 0)", "chart-5": "oklch(0.269 0 0)",
        },
        "radius": {"sm": 6, "md": 8, "lg": 10, "xl": 14},
        "radius_control": "md", "radius_surface": "xl",
        "type": {"xs": 12, "sm": 14, "base": 16, "lg": 18, "xl": 20, "2xl": 24, "3xl": 30, "4xl": 36, "5xl": 48},
        "leading": {"tight": 1.2, "snug": 1.35, "normal": 1.5, "relaxed": 1.65},
        "tracking": {"tight": "-0.02em", "normal": "0em", "wide": "0.02em"},
        "control_h": {"sm": 32, "md": 36, "lg": 40}, "nav_h": 56, "row_h": {"compact": 36, "comfortable": 48},
        "button": {"weight": 500, "case": "none", "tracking": "0em", "font": "ui"},
        "shadow_light": {"xs": "0 1px 2px 0 oklch(0 0 0 / 5%)", "sm": "0 1px 3px 0 oklch(0 0 0 / 10%), 0 1px 2px -1px oklch(0 0 0 / 10%)",
                          "md": "0 4px 6px -1px oklch(0 0 0 / 10%), 0 2px 4px -2px oklch(0 0 0 / 10%)", "lg": "0 10px 15px -3px oklch(0 0 0 / 10%), 0 4px 6px -4px oklch(0 0 0 / 10%)"},
        "shadow_dark": {"xs": "0 1px 2px 0 oklch(0 0 0 / 30%)", "sm": "0 1px 3px 0 oklch(0 0 0 / 40%)",
                         "md": "0 4px 8px -2px oklch(0 0 0 / 45%)", "lg": "0 12px 24px -6px oklch(0 0 0 / 55%)"},
        "motion": {"fast": "100ms", "base": "150ms", "slow": "250ms", "standard": "cubic-bezier(0.2, 0, 0, 1)", "out": "cubic-bezier(0, 0, 0.2, 1)", "emphasis": "cubic-bezier(0.3, 0, 0, 1.2)"},
        "credits": [SHADCN_CREDIT, OD_CREDIT, LUCIDE_CREDIT],
        "prose": {
            "overview": "Neutral is the system TeleDesign attaches when a project has none. It takes shadcn/ui's neutral theme as-is (every colour value below comes from shadcn/ui's MIT-licensed v4 registry) and adds the pieces a design agent needs that a component library leaves implicit: a type scale, a spacing scale, elevation, motion and written rules.\n\n**Voice:** calm, functional, quietly confident. Content first, chrome second. Sentence case everywhere; verbs on buttons (\"Save changes\", not \"OK\"). No exclamation marks in UI copy.",
            "colour": "Achromatic by design: the primary is near-black in light mode and near-white in dark, so hierarchy is carried by value, not hue. The only chromatic tokens are the status colours (destructive / success / warning). If a brief wants a brand colour, change `--primary` and `--ring` only — everything else is built to stay grey. Never pure black text on pure white at display sizes >= 48px; use `--foreground` (0.145) which is already slightly lifted.",
            "typography": "One family (Inter) for display, body and UI; JetBrains Mono for code and tabular IDs. Weight does the work: 600 for headings, 500 for controls and labels, 400 for body. No more than three sizes on one screen. Tighten tracking (`--tracking-tight`) at 30px and up.",
            "spacing": "4px grid. Inside components use `--space-2`..`--space-4`; between groups `--space-6`/`--space-8`; between page sections `--space-16`..`--space-24`. Layout: 12 columns, 1200px max content width, 24px gutters; 8 columns at 640-1023px; 4 columns below 640px.",
            "radius": "Derived from shadcn's `--radius: 0.625rem`: sm 6, md 8 (controls), lg 10, xl 14 (cards, dialogs). Pills (`--radius-full`) only for badges and avatars.",
            "elevation": "Mostly flat: cards use a 1px `--border` and `--shadow-xs`. Popovers and menus use `--shadow-md`, dialogs `--shadow-lg`. No glassmorphism, no coloured shadows.",
            "motion": "Short and functional: 100-250ms, `--ease-standard`. Animate opacity and transform only. Respect `prefers-reduced-motion` by dropping transforms and keeping fades.",
            "iconography": "Lucide, 16px in controls and 20px in navigation, 1.5-2px stroke, `currentColor`. Icons sit left of labels with `--space-2` gap. Icon-only buttons need an `aria-label`.",
            "imagery": "Product screenshots and plain photography with neutral grading. No stock illustrations, no gradient blobs. Placeholder imagery is a `--muted` block with a centred caption, never a fake photo.",
            "components": "Primary buttons are solid `--primary`; secondary is `--secondary`; outline is a 1px `--border` on `--background`; ghost has no chrome until hover. Inputs are 36px with a 1px `--input` border and a 3px `--ring` at 50% on focus. Tables are borderless except for row dividers. Tabs default to a pill track on `--muted`.",
            "gaps": ["No sidebar tokens (shadcn ships `--sidebar-*`; use `--card`/`--muted` instead).", "Chart palette is greyscale (shadcn neutral default); pick a chromatic chart set per project if data needs to be distinguished by hue.", "`--success` / `--warning` / `--destructive-foreground` are TeleDesign additions, not shadcn tokens.", "No data-viz, date-picker, toast or combobox specimens yet."],
            "do": ["Let whitespace separate groups; add dividers only between unrelated sections.", "Use at most one primary button per view.", "Do not invent colour values outside the token set — if a brief needs one, leave a visible TODO comment and use the closest token."],
            "dont": ["No gradients on surfaces.", "No drop shadows on inputs.", "No more than three type sizes per screen."],
        },
    },
    # ────────────────────────────────────────────────────────────── editorial
    {
        "slug": "editorial", "name": "Editorial", "is_default": False, "default_theme": "light",
        "description": "Warm paper, ink and an oxblood accent. Serif display (Fraunces) over a serif text face (Source Serif 4), tight radii and generous measure — for long reads, reports, portfolios and magazine-style landing pages.",
        "tags": ["serif", "warm", "magazine", "longform", "report"],
        "fonts": {"display": "Fraunces", "body": "Source Serif 4", "ui": "Instrument Sans", "mono": "IBM Plex Mono"},
        "light": {
            "background": "oklch(0.975 0.012 85)", "foreground": "oklch(0.22 0.02 50)",
            "card": "oklch(0.99 0.008 85)", "card-foreground": "oklch(0.22 0.02 50)",
            "popover": "oklch(0.99 0.008 85)", "popover-foreground": "oklch(0.22 0.02 50)",
            "primary": "oklch(0.42 0.13 28)", "primary-foreground": "oklch(0.98 0.01 85)",
            "secondary": "oklch(0.93 0.02 80)", "secondary-foreground": "oklch(0.28 0.03 50)",
            "muted": "oklch(0.945 0.015 80)", "muted-foreground": "oklch(0.5 0.03 60)",
            "accent": "oklch(0.9 0.05 75)", "accent-foreground": "oklch(0.3 0.05 60)",
            "destructive": "oklch(0.52 0.19 27)", "destructive-foreground": "oklch(0.98 0.01 85)",
            "success": "oklch(0.5 0.1 150)", "success-foreground": "oklch(0.98 0.01 85)",
            "warning": "oklch(0.72 0.14 75)", "warning-foreground": "oklch(0.26 0.04 60)",
            "border": "oklch(0.86 0.02 75)", "input": "oklch(0.83 0.022 75)", "ring": "oklch(0.42 0.13 28)",
            "chart-1": "oklch(0.42 0.13 28)", "chart-2": "oklch(0.7 0.12 75)", "chart-3": "oklch(0.55 0.08 120)",
            "chart-4": "oklch(0.45 0.04 240)", "chart-5": "oklch(0.62 0.1 45)",
        },
        "dark": {
            "background": "oklch(0.19 0.012 60)", "foreground": "oklch(0.93 0.015 85)",
            "card": "oklch(0.23 0.014 60)", "card-foreground": "oklch(0.93 0.015 85)",
            "popover": "oklch(0.25 0.015 60)", "popover-foreground": "oklch(0.93 0.015 85)",
            "primary": "oklch(0.7 0.13 32)", "primary-foreground": "oklch(0.18 0.02 40)",
            "secondary": "oklch(0.29 0.015 60)", "secondary-foreground": "oklch(0.92 0.015 85)",
            "muted": "oklch(0.27 0.012 60)", "muted-foreground": "oklch(0.72 0.02 75)",
            "accent": "oklch(0.33 0.04 70)", "accent-foreground": "oklch(0.93 0.015 85)",
            "destructive": "oklch(0.68 0.17 25)", "destructive-foreground": "oklch(0.18 0.02 40)",
            "success": "oklch(0.72 0.11 150)", "success-foreground": "oklch(0.18 0.02 40)",
            "warning": "oklch(0.8 0.13 80)", "warning-foreground": "oklch(0.22 0.03 60)",
            "border": "oklch(0.93 0.015 85 / 12%)", "input": "oklch(0.93 0.015 85 / 18%)", "ring": "oklch(0.7 0.13 32)",
            "chart-1": "oklch(0.7 0.13 32)", "chart-2": "oklch(0.8 0.12 80)", "chart-3": "oklch(0.7 0.09 125)",
            "chart-4": "oklch(0.68 0.05 240)", "chart-5": "oklch(0.74 0.09 50)",
        },
        "radius": {"sm": 2, "md": 3, "lg": 4, "xl": 6},
        "radius_control": "sm", "radius_surface": "md",
        "type": {"xs": 13, "sm": 15, "base": 18, "lg": 21, "xl": 24, "2xl": 30, "3xl": 40, "4xl": 56, "5xl": 76},
        "leading": {"tight": 1.08, "snug": 1.25, "normal": 1.6, "relaxed": 1.75},
        "tracking": {"tight": "-0.025em", "normal": "0em", "wide": "0.08em"},
        "control_h": {"sm": 32, "md": 40, "lg": 48}, "nav_h": 64, "row_h": {"compact": 40, "comfortable": 52},
        "button": {"weight": 600, "case": "uppercase", "tracking": "0.08em", "font": "ui"},
        "shadow_light": {"xs": "0 1px 0 0 oklch(0.4 0.03 60 / 8%)", "sm": "0 1px 2px 0 oklch(0.4 0.03 60 / 10%)",
                          "md": "0 6px 16px -6px oklch(0.35 0.04 50 / 18%)", "lg": "0 18px 40px -12px oklch(0.3 0.04 50 / 24%)"},
        "shadow_dark": {"xs": "0 1px 0 0 oklch(0 0 0 / 30%)", "sm": "0 1px 2px 0 oklch(0 0 0 / 40%)",
                         "md": "0 6px 16px -6px oklch(0 0 0 / 50%)", "lg": "0 18px 40px -12px oklch(0 0 0 / 60%)"},
        "motion": {"fast": "150ms", "base": "240ms", "slow": "420ms", "standard": "cubic-bezier(0.25, 0.1, 0.25, 1)", "out": "cubic-bezier(0.16, 1, 0.3, 1)", "emphasis": "cubic-bezier(0.65, 0, 0.35, 1)"},
        "credits": [LUCIDE_CREDIT],
        "prose": {
            "overview": "Editorial treats the screen like a printed page: warm off-white paper, dark brown-black ink, one oxblood accent used the way a magazine uses a second colour. Hierarchy comes from typographic contrast (a high-contrast display serif against a sturdy text serif), rules and whitespace rather than boxes.\n\n**Voice:** considered, literate, a little dry. Headlines can be declarative sentences. Kickers (small caps labels above headlines) name the section. Captions are full sentences. Avoid marketing superlatives.",
            "colour": "Paper (`--background`), ink (`--foreground`) and oxblood (`--primary`) carry 95% of every layout. Ochre (`--accent`) is a highlighter wash for pull quotes and callouts, never for text. Status colours are muted to sit on paper. Dark mode is \"reading lamp\": warm charcoal, not blue-black.",
            "typography": "Fraunces for display (600-700, tight leading 1.08, negative tracking at 40px+); Source Serif 4 for body at 18px with 1.6 leading and a 62-72ch measure; Instrument Sans for UI chrome (buttons, labels, table headers, nav) so controls read as controls; IBM Plex Mono for figures in tables and code. Kickers: `--font-ui`, `--text-xs`, uppercase, `--tracking-wide`. Use italic Source Serif for standfirsts.",
            "spacing": "Same 4px grid, used generously. Section spacing `--space-20`/`--space-24`. Text columns max 680px; wide layouts use an asymmetric 12-col grid (text on 7, marginalia on 3). Hairline rules (1px `--border`) separate sections instead of cards.",
            "radius": "Nearly square: 2px controls, 3-4px surfaces. Images are never rounded.",
            "elevation": "Paper does not float. Default is flat with rules; `--shadow-md`/`--shadow-lg` are reserved for popovers and dialogs and use a warm-tinted shadow colour.",
            "motion": "Slow and quiet: 150-420ms, long ease-out. Fades and short rises (8px). No bounces, no parallax.",
            "iconography": "Sparse. Lucide at 1.5px stroke, 16px, only where a word would not do (close, search, external link). Never decorative.",
            "imagery": "Photography first — documentary, natural light, full-bleed or on the grid with a caption. Duotone (ink + paper) is acceptable for archival images. Figures and charts use the chart tokens with thin 1px strokes.",
            "components": "Buttons are uppercase, letter-spaced Instrument Sans with square-ish corners; primary is oxblood, secondary is a paper-tone fill. Cards are open: a top rule, a kicker, a serif headline — no heavy box. Tabs use the underline variant by default. Tables use rules only, serif body, mono figures, right-aligned numerics.",
            "gaps": ["No drop-cap or pull-quote component yet (build with tokens: `--font-display`, `--primary`).", "Fraunces' optical-size axis is not requested from Google Fonts (wght only) to keep payload small.", "No footnote / sidenote specimen."],
            "do": ["Keep body text at `--text-base` (18px) with a 62-72ch measure.", "Use one oxblood element per viewport as the focal point.", "Prefer rules and whitespace over boxes."],
            "dont": ["No rounded image corners.", "No bright saturated colours or gradients.", "No sans-serif headlines."],
        },
    },
    # ────────────────────────────────────────────────────────────── midnight
    {
        "slug": "midnight", "name": "Midnight", "is_default": False, "default_theme": "dark",
        "description": "Dark-first product/SaaS system: blue-black surfaces, an indigo primary with a cyan secondary signal, Manrope throughout. For app shells, dashboards, developer-facing marketing and anything shown on a projector.",
        "tags": ["dark", "saas", "product", "dashboard", "marketing"],
        "fonts": {"display": "Manrope", "body": "Manrope", "ui": "Manrope", "mono": "JetBrains Mono"},
        "dark": {
            "background": "oklch(0.16 0.02 270)", "foreground": "oklch(0.96 0.01 270)",
            "card": "oklch(0.2 0.025 270)", "card-foreground": "oklch(0.96 0.01 270)",
            "popover": "oklch(0.22 0.028 270)", "popover-foreground": "oklch(0.96 0.01 270)",
            "primary": "oklch(0.56 0.2 275)", "primary-foreground": "oklch(0.99 0.005 270)",
            "secondary": "oklch(0.26 0.03 270)", "secondary-foreground": "oklch(0.95 0.01 270)",
            "muted": "oklch(0.24 0.025 270)", "muted-foreground": "oklch(0.7 0.03 270)",
            "accent": "oklch(0.3 0.06 275)", "accent-foreground": "oklch(0.96 0.01 270)",
            "destructive": "oklch(0.66 0.21 22)", "destructive-foreground": "oklch(0.16 0.02 270)",
            "success": "oklch(0.74 0.16 160)", "success-foreground": "oklch(0.18 0.03 160)",
            "warning": "oklch(0.8 0.15 80)", "warning-foreground": "oklch(0.2 0.04 70)",
            "border": "oklch(1 0 0 / 9%)", "input": "oklch(1 0 0 / 14%)", "ring": "oklch(0.66 0.19 275)",
            "chart-1": "oklch(0.66 0.19 275)", "chart-2": "oklch(0.78 0.13 200)", "chart-3": "oklch(0.74 0.16 160)",
            "chart-4": "oklch(0.8 0.15 80)", "chart-5": "oklch(0.68 0.2 330)",
        },
        "light": {
            "background": "oklch(0.985 0.004 270)", "foreground": "oklch(0.2 0.03 270)",
            "card": "oklch(1 0 0)", "card-foreground": "oklch(0.2 0.03 270)",
            "popover": "oklch(1 0 0)", "popover-foreground": "oklch(0.2 0.03 270)",
            "primary": "oklch(0.52 0.2 275)", "primary-foreground": "oklch(0.99 0.005 270)",
            "secondary": "oklch(0.95 0.01 270)", "secondary-foreground": "oklch(0.25 0.03 270)",
            "muted": "oklch(0.955 0.008 270)", "muted-foreground": "oklch(0.5 0.03 270)",
            "accent": "oklch(0.94 0.03 275)", "accent-foreground": "oklch(0.3 0.1 275)",
            "destructive": "oklch(0.58 0.22 25)", "destructive-foreground": "oklch(0.99 0.005 270)",
            "success": "oklch(0.52 0.13 160)", "success-foreground": "oklch(0.99 0.005 270)",
            "warning": "oklch(0.72 0.15 75)", "warning-foreground": "oklch(0.22 0.04 70)",
            "border": "oklch(0.91 0.01 270)", "input": "oklch(0.88 0.012 270)", "ring": "oklch(0.52 0.2 275)",
            "chart-1": "oklch(0.52 0.2 275)", "chart-2": "oklch(0.62 0.12 210)", "chart-3": "oklch(0.58 0.14 160)",
            "chart-4": "oklch(0.72 0.15 75)", "chart-5": "oklch(0.58 0.2 330)",
        },
        "radius": {"sm": 6, "md": 8, "lg": 12, "xl": 16},
        "radius_control": "md", "radius_surface": "lg",
        "type": {"xs": 12, "sm": 14, "base": 15, "lg": 17, "xl": 20, "2xl": 24, "3xl": 32, "4xl": 44, "5xl": 60},
        "leading": {"tight": 1.1, "snug": 1.3, "normal": 1.55, "relaxed": 1.7},
        "tracking": {"tight": "-0.03em", "normal": "-0.005em", "wide": "0.04em"},
        "control_h": {"sm": 32, "md": 36, "lg": 44}, "nav_h": 60, "row_h": {"compact": 36, "comfortable": 48},
        "button": {"weight": 600, "case": "none", "tracking": "-0.005em", "font": "ui"},
        "shadow_light": {"xs": "0 1px 2px 0 oklch(0.2 0.05 270 / 6%)", "sm": "0 1px 3px 0 oklch(0.2 0.05 270 / 10%)",
                          "md": "0 8px 20px -6px oklch(0.2 0.05 270 / 16%)", "lg": "0 20px 44px -12px oklch(0.2 0.05 270 / 24%)"},
        "shadow_dark": {"xs": "0 0 0 1px oklch(1 0 0 / 4%)", "sm": "0 1px 2px 0 oklch(0 0 0 / 50%), 0 0 0 1px oklch(1 0 0 / 5%)",
                         "md": "0 10px 24px -8px oklch(0 0 0 / 60%), 0 0 0 1px oklch(1 0 0 / 6%)", "lg": "0 24px 56px -16px oklch(0 0 0 / 70%), 0 0 0 1px oklch(1 0 0 / 7%)"},
        "motion": {"fast": "120ms", "base": "180ms", "slow": "320ms", "standard": "cubic-bezier(0.2, 0, 0, 1)", "out": "cubic-bezier(0.16, 1, 0.3, 1)", "emphasis": "cubic-bezier(0.34, 1.3, 0.64, 1)"},
        "credits": [LUCIDE_CREDIT],
        "prose": {
            "overview": "Midnight is designed dark and translated to light, not the other way round — `:root` holds the dark values. Surfaces step up in lightness (background 0.16 → card 0.20 → popover 0.22) instead of relying on shadows, borders are white at 9% so they read on any surface, and a single indigo primary does the pointing.\n\n**Voice:** crisp, confident, technical-but-human. Short headlines (<= 8 words), concrete verbs, numbers over adjectives. Product names and features in sentence case.",
            "colour": "Indigo (`--primary`) for primary actions, selection and focus; cyan (`--chart-2`) is the secondary signal for charts and highlights and must not be used for buttons. Status colours are bright enough to read on 0.16 lightness. In light mode the primary deepens to 0.52 to hold 4.5:1 on white. Hero glows are allowed only as a radial gradient of `--primary` at <= 25% opacity behind a headline — one per page.",
            "typography": "Manrope everywhere (700-800 for display, 600 for UI, 400-500 for body) with slightly negative tracking; JetBrains Mono for keys, IDs, code and metric deltas. Base size 15px — Manrope is wide, 15 reads like 16 elsewhere. Display tracking -0.03em.",
            "spacing": "4px grid; app shells at `--space-4`/`--space-6` padding, marketing sections at `--space-24`. 12-col grid, 1240px max width, 24px gutters. Sidebar 240px, top bar `--nav-h` (60px).",
            "radius": "8px controls, 12px cards, 16px dialogs and hero media. Badges are pills.",
            "elevation": "Lightness steps first, shadow second. In dark mode shadows include a 1px white 4-7% outline ring so raised surfaces separate from the background; in light mode shadows are cool-tinted.",
            "motion": "180ms standard, 320ms for panels and dialogs with `--ease-out`; one springy `--ease-emphasis` for toggles and success states. Keep list animations under 40ms stagger.",
            "iconography": "Lucide, 16/20px, 1.75px stroke, `currentColor`; icons in `--muted-foreground` unless active.",
            "imagery": "Product UI screenshots on `--card` with a 1px border and `--radius-xl`; abstract imagery limited to the single primary glow. No photos of people at laptops.",
            "components": "Primary buttons are indigo with white text; secondary is a raised `--secondary` surface; ghost is the default for toolbars. Inputs sit on `--background` with a translucent `--input` border and an indigo ring. Cards are `--card` with a border, no shadow, 12px radius. Tabs default to pill. Tables are compact with sticky headers in `--muted`.",
            "gaps": ["No command-palette, sidebar or toast specimens yet.", "Light theme is a translation and has had less review than dark.", "Glow effect is described, not tokenised."],
            "do": ["Start from `[data-theme=\"dark\"]`; check the light theme second.", "Use lightness steps (background → card → popover) to express depth.", "Keep cyan for data, indigo for action."],
            "dont": ["No pure black (#000) backgrounds.", "No more than one glow per page.", "No coloured text on coloured surfaces other than the documented foreground pairs."],
        },
    },
    # ────────────────────────────────────────────────────────────── playful
    {
        "slug": "playful", "name": "Playful", "is_default": False, "default_theme": "light",
        "description": "Rounded, saturated consumer system: cream background, coral primary, lavender and lemon supporting colours, Fredoka display with Nunito text, pill buttons and springy motion. For consumer apps, onboarding, education and campaigns.",
        "tags": ["consumer", "rounded", "saturated", "friendly", "onboarding"],
        "fonts": {"display": "Fredoka", "body": "Nunito", "ui": "Nunito", "mono": "DM Mono"},
        "light": {
            "background": "oklch(0.985 0.012 95)", "foreground": "oklch(0.25 0.04 290)",
            "card": "oklch(1 0 0)", "card-foreground": "oklch(0.25 0.04 290)",
            "popover": "oklch(1 0 0)", "popover-foreground": "oklch(0.25 0.04 290)",
            "primary": "oklch(0.57 0.2 28)", "primary-foreground": "oklch(0.99 0.005 95)",
            "secondary": "oklch(0.92 0.06 300)", "secondary-foreground": "oklch(0.35 0.13 300)",
            "muted": "oklch(0.955 0.02 95)", "muted-foreground": "oklch(0.5 0.04 290)",
            "accent": "oklch(0.93 0.12 100)", "accent-foreground": "oklch(0.32 0.06 90)",
            "destructive": "oklch(0.58 0.22 20)", "destructive-foreground": "oklch(0.99 0.005 95)",
            "success": "oklch(0.53 0.14 152)", "success-foreground": "oklch(0.99 0.005 95)",
            "warning": "oklch(0.82 0.16 78)", "warning-foreground": "oklch(0.3 0.06 60)",
            "border": "oklch(0.9 0.025 290)", "input": "oklch(0.86 0.03 290)", "ring": "oklch(0.57 0.2 28)",
            "chart-1": "oklch(0.66 0.19 30)", "chart-2": "oklch(0.6 0.2 300)", "chart-3": "oklch(0.86 0.16 100)",
            "chart-4": "oklch(0.75 0.14 165)", "chart-5": "oklch(0.7 0.13 235)",
        },
        "dark": {
            "background": "oklch(0.2 0.04 290)", "foreground": "oklch(0.97 0.01 95)",
            "card": "oklch(0.25 0.05 290)", "card-foreground": "oklch(0.97 0.01 95)",
            "popover": "oklch(0.27 0.055 290)", "popover-foreground": "oklch(0.97 0.01 95)",
            "primary": "oklch(0.72 0.18 30)", "primary-foreground": "oklch(0.2 0.04 290)",
            "secondary": "oklch(0.34 0.09 300)", "secondary-foreground": "oklch(0.95 0.02 300)",
            "muted": "oklch(0.28 0.045 290)", "muted-foreground": "oklch(0.76 0.03 290)",
            "accent": "oklch(0.86 0.15 100)", "accent-foreground": "oklch(0.22 0.04 90)",
            "destructive": "oklch(0.7 0.19 22)", "destructive-foreground": "oklch(0.2 0.04 290)",
            "success": "oklch(0.76 0.16 152)", "success-foreground": "oklch(0.2 0.04 290)",
            "warning": "oklch(0.85 0.15 82)", "warning-foreground": "oklch(0.24 0.05 70)",
            "border": "oklch(1 0 0 / 12%)", "input": "oklch(1 0 0 / 18%)", "ring": "oklch(0.72 0.18 30)",
            "chart-1": "oklch(0.72 0.18 30)", "chart-2": "oklch(0.7 0.18 300)", "chart-3": "oklch(0.88 0.15 100)",
            "chart-4": "oklch(0.8 0.13 165)", "chart-5": "oklch(0.76 0.12 235)",
        },
        "radius": {"sm": 10, "md": 14, "lg": 20, "xl": 28},
        "radius_control": "full", "radius_surface": "xl",
        "type": {"xs": 13, "sm": 15, "base": 17, "lg": 19, "xl": 22, "2xl": 28, "3xl": 36, "4xl": 48, "5xl": 64},
        "leading": {"tight": 1.1, "snug": 1.3, "normal": 1.55, "relaxed": 1.7},
        "tracking": {"tight": "-0.01em", "normal": "0em", "wide": "0.03em"},
        "control_h": {"sm": 36, "md": 44, "lg": 52}, "nav_h": 68, "row_h": {"compact": 44, "comfortable": 56},
        "button": {"weight": 800, "case": "none", "tracking": "0.01em", "font": "ui"},
        "shadow_light": {"xs": "0 2px 0 0 oklch(0.25 0.04 290 / 8%)", "sm": "0 3px 0 0 oklch(0.25 0.04 290 / 10%)",
                          "md": "0 6px 0 -1px oklch(0.25 0.04 290 / 10%), 0 12px 24px -8px oklch(0.25 0.04 290 / 16%)", "lg": "0 10px 0 -2px oklch(0.25 0.04 290 / 10%), 0 24px 48px -12px oklch(0.25 0.04 290 / 22%)"},
        "shadow_dark": {"xs": "0 2px 0 0 oklch(0 0 0 / 30%)", "sm": "0 3px 0 0 oklch(0 0 0 / 35%)",
                         "md": "0 6px 0 -1px oklch(0 0 0 / 35%), 0 12px 24px -8px oklch(0 0 0 / 50%)", "lg": "0 10px 0 -2px oklch(0 0 0 / 35%), 0 24px 48px -12px oklch(0 0 0 / 60%)"},
        "motion": {"fast": "140ms", "base": "220ms", "slow": "360ms", "standard": "cubic-bezier(0.3, 0, 0.2, 1)", "out": "cubic-bezier(0.22, 1, 0.36, 1)", "emphasis": "cubic-bezier(0.34, 1.56, 0.64, 1)"},
        "credits": [LUCIDE_CREDIT],
        "prose": {
            "overview": "Playful is chunky and warm: a cream page, bold coral actions, candy-coloured supporting fills and soft \"stacked\" shadows (a hard offset plus a soft blur) that make surfaces feel tactile. Everything is rounded; controls are pills.\n\n**Voice:** friendly, encouraging, second person. Short sentences, contractions, one emoji at most per screen (never in buttons). Celebrate completions; never blame the user in errors (\"That code didn't work — try again?\").",
            "colour": "Coral (`--primary`) is the action colour; lavender (`--secondary`) is for secondary actions and selected states; lemon (`--accent`) is a highlight fill for badges, stickers and marker-style emphasis behind words. Use colour in blocks — a whole card in `--secondary` is fine — but keep one coral CTA per view. Coral sits at 0.57 lightness so white labels just clear 4.5:1; buttons are still 800 weight so the label reads at small sizes.",
            "typography": "Fredoka (600-700) for display and numbers — round terminals match the radii; Nunito for body (400) and UI (700-800); DM Mono for codes and vouchers. Base 17px. Headlines are short and can break onto two lines deliberately.",
            "spacing": "Roomy 4px grid: component padding `--space-4`-`--space-6`, card gaps `--space-6`, section spacing `--space-20`. Touch targets >= 44px (the md control height).",
            "radius": "10 / 14 / 20 / 28px; controls use `--radius-full` (pills); cards and sheets use 28px. Images get `--radius-lg` or are cut into blobs with SVG masks.",
            "elevation": "\"Stacked\" shadows: a hard 2-10px downward offset in foreground at 8-10% plus a soft blur, like a sticker lifted off paper. Buttons press down (translateY 2px, shadow shrinks) on :active.",
            "motion": "Springy: `--ease-emphasis` (overshoot) for entrances, toggles, checkmarks and counters; 140-360ms. Allowed: small rotations (±3°) on stickers, confetti on completion. Respect reduced motion by switching springs to `--ease-standard`.",
            "iconography": "Lucide at 2-2.25px stroke with round caps, 20-24px, often inside a 40px tinted circle (`--secondary` or `--accent`).",
            "imagery": "Flat, colourful illustration and cut-out photography on tinted blocks. People smiling at the camera are fine here. Avoid dark or moody photos.",
            "components": "Pill buttons with heavy labels and a stacked shadow; primary coral, secondary lavender, outline uses a 2px border. Inputs are 44px, 2px border, pill-ish (`--radius-md`). Cards are white on cream with 28px radius and stacked shadow. Badges are lemon/lavender stickers. Tabs default to pill. Tables are comfortable density with zebra striping.",
            "gaps": ["No illustration set is bundled — pick an OFL/CC0 set per project.", "Confetti / celebration is described, not a component.", "Coral + white is only just above 4.5:1; do not set small regular-weight coral text on white either."],
            "do": ["Keep one coral CTA per view.", "Use tinted circles behind icons.", "Round everything — no square corners anywhere."],
            "dont": ["No thin (<400) weights.", "No grey-on-grey low-contrast text.", "No emoji inside buttons or form labels."],
        },
    },
    # ────────────────────────────────────────────────────────────── technical
    {
        "slug": "technical", "name": "Technical", "is_default": False, "default_theme": "light",
        "description": "Dense developer-tool system: cool greys, a teal signal colour, IBM Plex Sans with IBM Plex Mono accents, 4px radii and compact 30px controls. For consoles, admin panels, docs, logs and data-heavy tables.",
        "tags": ["developer", "dense", "mono", "admin", "docs", "data"],
        "fonts": {"display": "IBM Plex Sans", "body": "IBM Plex Sans", "ui": "IBM Plex Sans", "mono": "IBM Plex Mono"},
        "light": {
            "background": "oklch(0.99 0.002 250)", "foreground": "oklch(0.2 0.01 250)",
            "card": "oklch(1 0 0)", "card-foreground": "oklch(0.2 0.01 250)",
            "popover": "oklch(1 0 0)", "popover-foreground": "oklch(0.2 0.01 250)",
            "primary": "oklch(0.5 0.11 170)", "primary-foreground": "oklch(0.99 0.002 250)",
            "secondary": "oklch(0.955 0.004 250)", "secondary-foreground": "oklch(0.25 0.012 250)",
            "muted": "oklch(0.965 0.003 250)", "muted-foreground": "oklch(0.5 0.012 250)",
            "accent": "oklch(0.95 0.03 170)", "accent-foreground": "oklch(0.32 0.07 170)",
            "destructive": "oklch(0.55 0.2 27)", "destructive-foreground": "oklch(0.99 0.002 250)",
            "success": "oklch(0.53 0.13 150)", "success-foreground": "oklch(0.99 0.002 250)",
            "warning": "oklch(0.72 0.14 70)", "warning-foreground": "oklch(0.24 0.04 60)",
            "border": "oklch(0.9 0.005 250)", "input": "oklch(0.86 0.007 250)", "ring": "oklch(0.5 0.11 170)",
            "chart-1": "oklch(0.55 0.11 170)", "chart-2": "oklch(0.74 0.14 75)", "chart-3": "oklch(0.58 0.13 245)",
            "chart-4": "oklch(0.6 0.17 340)", "chart-5": "oklch(0.6 0.01 250)",
        },
        "dark": {
            "background": "oklch(0.17 0.006 250)", "foreground": "oklch(0.93 0.005 250)",
            "card": "oklch(0.2 0.007 250)", "card-foreground": "oklch(0.93 0.005 250)",
            "popover": "oklch(0.22 0.008 250)", "popover-foreground": "oklch(0.93 0.005 250)",
            "primary": "oklch(0.76 0.13 170)", "primary-foreground": "oklch(0.17 0.02 170)",
            "secondary": "oklch(0.26 0.008 250)", "secondary-foreground": "oklch(0.93 0.005 250)",
            "muted": "oklch(0.24 0.007 250)", "muted-foreground": "oklch(0.67 0.01 250)",
            "accent": "oklch(0.28 0.04 170)", "accent-foreground": "oklch(0.9 0.05 170)",
            "destructive": "oklch(0.67 0.19 25)", "destructive-foreground": "oklch(0.17 0.006 250)",
            "success": "oklch(0.74 0.15 150)", "success-foreground": "oklch(0.17 0.006 250)",
            "warning": "oklch(0.8 0.14 75)", "warning-foreground": "oklch(0.2 0.03 60)",
            "border": "oklch(1 0 0 / 10%)", "input": "oklch(1 0 0 / 15%)", "ring": "oklch(0.76 0.13 170)",
            "chart-1": "oklch(0.76 0.13 170)", "chart-2": "oklch(0.8 0.14 75)", "chart-3": "oklch(0.7 0.12 245)",
            "chart-4": "oklch(0.7 0.16 340)", "chart-5": "oklch(0.65 0.01 250)",
        },
        "radius": {"sm": 3, "md": 4, "lg": 6, "xl": 8},
        "radius_control": "md", "radius_surface": "lg",
        "type": {"xs": 11, "sm": 12, "base": 13, "lg": 14, "xl": 16, "2xl": 20, "3xl": 24, "4xl": 30, "5xl": 40},
        "leading": {"tight": 1.2, "snug": 1.3, "normal": 1.5, "relaxed": 1.6},
        "tracking": {"tight": "-0.01em", "normal": "0em", "wide": "0.06em"},
        "control_h": {"sm": 26, "md": 30, "lg": 36}, "nav_h": 44, "row_h": {"compact": 28, "comfortable": 36},
        "button": {"weight": 500, "case": "none", "tracking": "0em", "font": "ui"},
        "shadow_light": {"xs": "0 1px 1px 0 oklch(0.2 0.01 250 / 6%)", "sm": "0 1px 2px 0 oklch(0.2 0.01 250 / 10%)",
                          "md": "0 4px 10px -2px oklch(0.2 0.01 250 / 14%)", "lg": "0 12px 28px -8px oklch(0.2 0.01 250 / 22%)"},
        "shadow_dark": {"xs": "0 1px 1px 0 oklch(0 0 0 / 40%)", "sm": "0 1px 2px 0 oklch(0 0 0 / 50%)",
                         "md": "0 4px 12px -2px oklch(0 0 0 / 60%)", "lg": "0 12px 28px -8px oklch(0 0 0 / 70%)"},
        "motion": {"fast": "80ms", "base": "120ms", "slow": "200ms", "standard": "cubic-bezier(0.2, 0, 0, 1)", "out": "cubic-bezier(0, 0, 0.2, 1)", "emphasis": "cubic-bezier(0.2, 0, 0, 1)"},
        "credits": [LUCIDE_CREDIT],
        "prose": {
            "overview": "Technical is for people who read screens all day: small base size (13px), compact controls, a mono face for anything machine-generated (IDs, hashes, paths, timestamps, figures), and a single teal signal colour. Information density is a feature — but alignment, not decoration, is what keeps it readable.\n\n**Voice:** precise, terse, neutral. Imperative labels (\"Deploy\", \"Rotate key\"). State facts with units (\"3 replicas · 12 ms p95\"). Errors say what failed and what to do; include the error code in mono.",
            "colour": "Cool neutral greys carry the UI; teal (`--primary`) marks the primary action, the active nav item and focus. Status colours are semantic only — success/warning/destructive map to healthy/degraded/failed and are never decorative. Charts use the five chart tokens in order; `--chart-5` (grey) is \"other\". Syntax-highlighting colours are out of scope (see gaps).",
            "typography": "IBM Plex Sans for UI and prose (400/500/600), IBM Plex Mono for code, tabular figures, IDs and small uppercase section labels (`--text-xs`, `--tracking-wide`). Base 13px, 12px in tables, headings rarely above `--text-2xl`. Always `font-variant-numeric: tabular-nums` on numbers.",
            "spacing": "Dense 4px grid with 2px half-steps (`--space-0-5`, `--space-1-5`). Component padding `--space-2`/`--space-3`; panels `--space-4`. Layout is full-bleed: sidebar 220px, top bar `--nav-h` (44px), content fills the rest. Align everything to a column — ragged edges are the enemy of density.",
            "radius": "3-4px controls, 6px panels, 8px dialogs. Nothing pill-shaped except status dots.",
            "elevation": "Flat panels separated by 1px borders; shadows only for popovers, menus and dialogs. Sticky table headers use `--muted` with a bottom border, no shadow.",
            "motion": "Near-instant: 80-200ms, no overshoot. Motion communicates state (spinner, progress, row insert highlight), never delight.",
            "iconography": "Lucide 14-16px, 1.5px stroke, `--muted-foreground` by default. Status is a 8px dot plus a word, never colour alone.",
            "imagery": "Almost none. Diagrams (architecture, sequence) drawn with 1px strokes in `--border`/`--foreground`, mono labels. Terminal and code blocks on `--muted`.",
            "components": "Buttons are 30px, 500 weight, 4px radius; secondary is a bordered grey; ghost for toolbars. Inputs 30px with mono text for technical values. Badges are square-ish with mono uppercase labels. Tabs default to underline. Tables are compact (28px rows), mono numerics right-aligned, zebra off, hover row highlight on `--muted`.",
            "gaps": ["No syntax-highlighting palette; use a separate OFL/MIT theme if code blocks matter.", "No tree view, log viewer or key-value list specimens yet.", "11px `--text-xs` is below common accessibility guidance — keep it to labels, never body copy."],
            "do": ["Use mono for anything a machine produced.", "Right-align numerics and use tabular figures.", "Pair every status colour with a word or icon."],
            "dont": ["No large hero typography.", "No decorative colour — every hue means something.", "No rounded pills except status dots."],
        },
    },
]
